[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mas-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.135.1",
    "jinja2>=3.1.6",
    "joblib>=1.5.3",
    "numpy>=2.4.3",
    "pandas>=3.0.1",
    "pydantic>=2.12.5",
    "scikit-learn>=1.8.0",
    "uvicorn>=0.41.0",
    "xgboost>=3.2.0",
]
[project.scripts]
app = "house_price_prediction.webapp.main:app"
predict-prices = "house_price_prediction.cli:main"
serve-app = "house_price_prediction.webapp.main:start"
generate-visuals = "house_price_prediction.generate_visuals:generate_plots"

[tool.hatch.build.targets.wheel]
packages = ["src/house_price_prediction"]
